modLoader="javafml" 
loaderVersion="[36,)"
issueTrackerURL="https://github.com/noobanidus/threadsafety/issues"
license="https://github.com/noobanidus/lootr/blob/1.16/LICENSE"
[[mods]] 
modId="threadsafety"
version="${version}"
displayName="threadsafety"
displayURL="https://minecraft.curseforge.com/projects/thread-safety"
authors="Noobanidus"
description='''
A server-side mod that adds thread safety to the TemplateManager and WeightedBlockStateProvider.
'''
[[dependencies.threadsafety]]
    modId="forge" 
    mandatory=true 
    versionRange="[36,)"
    ordering="NONE"
    side="SERVER"
[[dependencies.threadsafety]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,)"
    ordering="NONE"
    side="SERVER"
